In [2]:
import pandas as pd

In [3]:
alpha=pd.read_pickle('df_1')

In [4]:
alpha

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,76001,1990-91,00,1610612757,POR,23.0,43,0,290,55,...,0.568,27,62,89,12,4,12,22,39,135
1,76001,1991-92,00,1610612757,POR,24.0,71,1,934,178,...,0.752,81,179,260,30,25,16,66,132,432
2,76001,1992-93,00,1610612749,MIL,25.0,12,0,159,26,...,0.75,12,25,37,10,6,4,13,24,64
3,76001,1992-93,00,1610612738,BOS,25.0,63,52,1152,219,...,0.76,114,186,300,17,19,22,84,165,514
4,76001,1992-93,00,0,TOT,25.0,75,52,1311,245,...,0.759,126,211,337,27,25,26,97,189,578
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,1626203,2017-18,00,1610612766,CHA,24.0,63,2,1050,96,...,0.695,42,79,121,59,33,2,27,109,273
2,1626203,2018-19,00,1610612751,BKN,25.0,35,21,715,64,...,0.818,23,84,107,34,13,7,17,68,184
3,1626203,2019-20,00,1610612750,MIN,26.0,33,20,663,62,...,0.73,29,71,100,30,17,2,19,66,171
4,1626203,2019-20,00,1610612737,ATL,26.0,22,0,266,25,...,0.474,22,28,50,15,7,4,10,36,72
5,1626203,2019-20,00,0,TOT,26.0,55,20,929,87,...,0.643,51,99,150,45,24,6,29,102,243

In [5]:
alpha['SEASON_COUNT']=alpha.groupby('PLAYER_ID')['SEASON_ID'].cumcount()+1

In [6]:
alpha.head()

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,SEASON_COUNT
0,76001,1990-91,00,1610612757,POR,23.0,43,0,290,55,...,27,62,89,12,4,12,22,39,135,1
1,76001,1991-92,00,1610612757,POR,24.0,71,1,934,178,...,81,179,260,30,25,16,66,132,432,2
2,76001,1992-93,00,1610612749,MIL,25.0,12,0,159,26,...,12,25,37,10,6,4,13,24,64,3
3,76001,1992-93,00,1610612738,BOS,25.0,63,52,1152,219,...,114,186,300,17,19,22,84,165,514,4
4,76001,1992-93,00,0,TOT,25.0,75,52,1311,245,...,126,211,337,27,25,26,97,189,578,5

In [7]:
firstthree=alpha[alpha['SEASON_COUNT']<4]
firstthree

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,SEASON_COUNT
0,76001,1990-91,00,1610612757,POR,23.0,43,0,290,55,...,27,62,89,12,4,12,22,39,135,1
1,76001,1991-92,00,1610612757,POR,24.0,71,1,934,178,...,81,179,260,30,25,16,66,132,432,2
2,76001,1992-93,00,1610612749,MIL,25.0,12,0,159,26,...,12,25,37,10,6,4,13,24,64,3
0,76002,1968-69,00,1610612749,MIL,23.0,29,None,837,126,...,NaN,NaN,378,33,NaN,NaN,NaN,98,320,1
1,76002,1968-69,00,1610612758,CIN,23.0,20,None,108,18,...,NaN,NaN,31,4,NaN,NaN,NaN,17,38,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,101211,2005-06,00,1610612741,CHI,24.0,3,0,20,1,...,0,3,3,1,0,0,1,3,5,2
2,101211,2005-06,00,1610612739,CLE,24.0,13,0,117,14,...,4,13,17,3,3,2,7,23,36,3
0,1626203,2016-17,00,1610612766,CHA,23.0,27,1,189,19,...,5,17,22,6,6,1,3,18,57,1
1,1626203,2017-18,00,1610612766,CHA,24.0,63,2,1050,96,...,42,79,121,59,33,2,27,109,273,2
2,1626203,2018-19,00,1610612751,BKN,25.0,35,21,715,64,...,23,84,107,34,13,7,17,68,184,3

In [8]:
ll=firstthree.groupby('PLAYER_ID')['SEASON_COUNT']

In [9]:
beta=pd.read_pickle('data/nbaseasonstats')
beta.rename(columns={'Name':'PLAYER'}, inplace=True)
beta.head()

,SEASON,AGE,TEAM,LEAGUE,POS,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,PLAYER
0,2020-21,19.0,GSW,NBA,C,39,27,21.4,4.9,9.4,...,1.4,4.4,5.8,0.7,0.3,0.9,1.5,3.1,11.5,James Wiseman
0,2020-21,19.0,DET,NBA,PG,26,18,25.8,2.7,7.7,...,0.2,2.4,2.7,5.3,1.0,0.4,3.2,2.2,6.8,Killian Hayes
0,2020-21,20.0,SAC,NBA,PG,58,20,30.1,5.0,10.7,...,0.7,2.3,3.0,5.3,1.3,0.5,1.6,1.4,13.0,Tyrese Haliburton
0,2020-21,19.0,CHO,NBA,PG,51,31,28.8,5.7,13.2,...,1.2,4.7,5.9,6.1,1.6,0.4,2.8,2.7,15.7,LaMelo Ball
0,2020-21,19.0,OKC,NBA,PF,45,28,24.2,3.1,9.1,...,0.7,4.0,4.7,2.2,0.4,0.9,2.2,1.3,8.2,Aleksej Pokusevski

In [10]:
beta['SEASON_COUNT']=beta.groupby('PLAYER')['SEASON'].cumcount()+1
beta.head()

,SEASON,AGE,TEAM,LEAGUE,POS,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,PLAYER,SEASON_COUNT
0,2020-21,19.0,GSW,NBA,C,39,27,21.4,4.9,9.4,...,4.4,5.8,0.7,0.3,0.9,1.5,3.1,11.5,James Wiseman,1
0,2020-21,19.0,DET,NBA,PG,26,18,25.8,2.7,7.7,...,2.4,2.7,5.3,1.0,0.4,3.2,2.2,6.8,Killian Hayes,1
0,2020-21,20.0,SAC,NBA,PG,58,20,30.1,5.0,10.7,...,2.3,3.0,5.3,1.3,0.5,1.6,1.4,13.0,Tyrese Haliburton,1
0,2020-21,19.0,CHO,NBA,PG,51,31,28.8,5.7,13.2,...,4.7,5.9,6.1,1.6,0.4,2.8,2.7,15.7,LaMelo Ball,1
0,2020-21,19.0,OKC,NBA,PF,45,28,24.2,3.1,9.1,...,4.0,4.7,2.2,0.4,0.9,2.2,1.3,8.2,Aleksej Pokusevski,1

In [13]:
threeseasons=beta[beta['SEASON_COUNT']<4]
threeseasons

,SEASON,AGE,TEAM,LEAGUE,POS,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,PLAYER,SEASON_COUNT
0,2020-21,19.0,GSW,NBA,C,39,27,21.4,4.9,9.4,...,4.4,5.8,0.7,0.3,0.9,1.5,3.1,11.5,James Wiseman,1
0,2020-21,19.0,DET,NBA,PG,26,18,25.8,2.7,7.7,...,2.4,2.7,5.3,1.0,0.4,3.2,2.2,6.8,Killian Hayes,1
0,2020-21,20.0,SAC,NBA,PG,58,20,30.1,5.0,10.7,...,2.3,3.0,5.3,1.3,0.5,1.6,1.4,13.0,Tyrese Haliburton,1
0,2020-21,19.0,CHO,NBA,PG,51,31,28.8,5.7,13.2,...,4.7,5.9,6.1,1.6,0.4,2.8,2.7,15.7,LaMelo Ball,1
0,2020-21,19.0,OKC,NBA,PF,45,28,24.2,3.1,9.1,...,4.0,4.7,2.2,0.4,0.9,2.2,1.3,8.2,Aleksej Pokusevski,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,1970-71,22.0,MIL,NBA,PG,53,NaN,7.5,0.9,2.5,...,NaN,0.9,1.4,NaN,NaN,NaN,0.6,2.2,Bill Zopf,1
0,2016-17,19.0,LAL,NBA,C,38.0,11.0,16.0,3.3,6.3,...,3.1,4.2,0.8,0.4,0.9,0.8,1.7,7.5,Ivica Zubac,1
1,2017-18,20.0,LAL,NBA,C,43.0,0.0,9.5,1.4,2.8,...,1.8,2.9,0.6,0.2,0.3,0.6,1.1,3.7,Ivica Zubac,2
2,2018-19,21.0,TOT,NBA,C,59.0,37.0,17.6,3.6,6.4,...,4.2,6.1,1.1,0.2,0.9,1.2,2.3,8.9,Ivica Zubac,3
0,1948-49,29.0,WSC,BAA,NaN,56,NaN,NaN,1.8,5.8,...,NaN,NaN,0.9,NaN,NaN,NaN,3.3,4.9,Matt Zunic,1

In [12]:
thirdseason=beta[beta['SEASON_COUNT']==3]
thirdseason

,SEASON,AGE,TEAM,LEAGUE,POS,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,PLAYER,SEASON_COUNT
2,2020-21,19.0,ORL,NBA,SG,26.0,1.0,25.2,4.3,9.7,...,4.2,5.0,2.8,0.6,0.3,1.6,1.5,11.2,R.J. Hampton,3
2,2020-21,22.0,PHI,NBA,SG,6.0,0.0,4.5,0.8,1.5,...,0.2,0.7,0.5,0.2,0.0,0.2,0.3,2.7,Mason Jones,3
2,2020-21,24.0,CLE,NBA,SG,28.0,1.0,13.4,1.3,3.6,...,1.5,1.8,0.9,0.5,0.3,0.6,1.3,4.1,Brodric Thomas,3
2,1992-93,24.0,TOT,NBA,PF,75.0,52.0,17.5,3.3,6.3,...,2.8,4.5,0.4,0.3,0.3,1.3,2.5,7.7,Alaa Abdelnaby,3
2,1968-69,22.0,MIL,NBA,C,29.0,NaN,28.9,4.3,12.0,...,NaN,13.0,1.1,NaN,NaN,NaN,3.4,11.0,Zaid Abdul-Aziz,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2,2014-15,25.0,BOS,NBA,C,82.0,59.0,21.1,4.1,7.5,...,3.9,5.7,1.4,0.2,0.6,0.9,2.5,10.2,Tyler Zeller,3
2,2002-03,25.0,LAC,NBA,C,41.0,1.0,10.0,1.5,4.0,...,1.2,1.9,0.2,0.2,0.2,0.8,1.0,4.4,Wang Zhizhi,3
2,1996-97,23.0,CHH,NBA,C,36.0,2.0,8.0,0.9,2.4,...,1.1,1.8,0.3,0.1,0.1,0.6,1.2,2.5,George Zidek,3
2,2019-20,23.0,CLE,NBA,C,22,0,10.0,1.9,3.3,...,2.2,3.0,0.3,0.3,0.2,0.5,1.2,4.4,Ante Zizic,3
2,2018-19,21.0,TOT,NBA,C,59.0,37.0,17.6,3.6,6.4,...,4.2,6.1,1.1,0.2,0.9,1.2,2.3,8.9,Ivica Zubac,3

In [13]:
df = pd.read_csv('data/allnb1', header=None)
df_drop=df.drop(columns=[0,2,3,4,5,6,7,8]).drop_duplicates(subset=[1])
df_drop.columns = df_drop.iloc[0]
df_drop=df_drop.iloc[1:, :]
df_drop['1ST_TEAMNBA']=1
df_drop

0                   PLAYER  1ST_TEAMNBA
1             LeBron James            1
2             James Harden            1
3            Anthony Davis            1
4    Giannis Antetokounmpo            1
5              Luka Doncic            1
..                     ...          ...
362          Howie Dallmar            1
363            Bob Feerick            1
365            Ed Sadowski            1
369         Bones McKinney            1
370            Stan Miasek            1

[110 rows x 2 columns]

In [14]:
dfx=pd.merge(thirdseason,df_drop,how='left')
dfx

,SEASON,AGE,TEAM,LEAGUE,POS,G,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,PLAYER,SEASON_COUNT,1ST_TEAMNBA
0,2020-21,19.0,ORL,NBA,SG,26.0,1.0,25.2,4.3,9.7,...,5.0,2.8,0.6,0.3,1.6,1.5,11.2,R.J. Hampton,3,NaN
1,2020-21,22.0,PHI,NBA,SG,6.0,0.0,4.5,0.8,1.5,...,0.7,0.5,0.2,0.0,0.2,0.3,2.7,Mason Jones,3,NaN
2,2020-21,24.0,CLE,NBA,SG,28.0,1.0,13.4,1.3,3.6,...,1.8,0.9,0.5,0.3,0.6,1.3,4.1,Brodric Thomas,3,NaN
3,1992-93,24.0,TOT,NBA,PF,75.0,52.0,17.5,3.3,6.3,...,4.5,0.4,0.3,0.3,1.3,2.5,7.7,Alaa Abdelnaby,3,NaN
4,1968-69,22.0,MIL,NBA,C,29.0,NaN,28.9,4.3,12.0,...,13.0,1.1,NaN,NaN,NaN,3.4,11.0,Zaid Abdul-Aziz,3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3076,2014-15,25.0,BOS,NBA,C,82.0,59.0,21.1,4.1,7.5,...,5.7,1.4,0.2,0.6,0.9,2.5,10.2,Tyler Zeller,3,NaN
3077,2002-03,25.0,LAC,NBA,C,41.0,1.0,10.0,1.5,4.0,...,1.9,0.2,0.2,0.2,0.8,1.0,4.4,Wang Zhizhi,3,NaN
3078,1996-97,23.0,CHH,NBA,C,36.0,2.0,8.0,0.9,2.4,...,1.8,0.3,0.1,0.1,0.6,1.2,2.5,George Zidek,3,NaN
3079,2019-20,23.0,CLE,NBA,C,22,0,10.0,1.9,3.3,...,3.0,0.3,0.3,0.2,0.5,1.2,4.4,Ante Zizic,3,NaN
3080,2018-19,21.0,TOT,NBA,C,59.0,37.0,17.6,3.6,6.4,...,6.1,1.1,0.2,0.9,1.2,2.3,8.9,Ivica Zubac,3,NaN

In [15]:
df2 = pd.read_csv('data/allnba2', header=None)
df_drop2=df2.drop(columns=[0,2,3,4,5,6,7,8]).drop_duplicates(subset=[1])
df_drop2.columns = df_drop2.iloc[0]
df_drop2=df_drop2.iloc[1:, :]
df_drop2['2nd_TEAMNBA']=1
df_drop2

0               PLAYER  2nd_TEAMNBA
1           Chris Paul            1
2        Kawhi Leonard            1
3       Damian Lillard            1
4         Nikola Jokic            1
5        Pascal Siakam            1
..                 ...          ...
363        Stan Miasek            1
364       Fred Scolari            1
365  Frankie Baumholtz            1
366    Ernie Calverley            1
367      Chick Halbert            1

[184 rows x 2 columns]

In [16]:
df3 = pd.read_csv('data/allnba3', header=None)
df_drop3=df3.drop(columns=[0,2,3,4,5,6,7,8]).drop_duplicates(subset=[1])
df_drop3.columns = df_drop3.iloc[0]
df_drop3=df_drop3.iloc[1:, :]
df_drop3['3rd_TEAMNBA']=1
df_drop3

0               PLAYER  3rd_TEAMNBA
1    Russell Westbrook            1
2         Jimmy Butler            1
3          Rudy Gobert            1
4          Ben Simmons            1
5         Jayson Tatum            1
..                 ...          ...
150       Bernard King            1
151       Chris Mullin            1
156     Terry Cummings            1
157         Dale Ellis            1
159      Robert Parish            1

[99 rows x 2 columns]

In [17]:
dfy=pd.merge(dfx,df_drop2,how='left')
dfz=pd.merge(dfy,df_drop3,how='left')
dfz

,SEASON,AGE,TEAM,LEAGUE,POS,G,GS,MP,FG,FGA,...,STL,BLK,TOV,PF,PTS,PLAYER,SEASON_COUNT,1ST_TEAMNBA,2nd_TEAMNBA,3rd_TEAMNBA
0,2020-21,19.0,ORL,NBA,SG,26.0,1.0,25.2,4.3,9.7,...,0.6,0.3,1.6,1.5,11.2,R.J. Hampton,3,NaN,NaN,NaN
1,2020-21,22.0,PHI,NBA,SG,6.0,0.0,4.5,0.8,1.5,...,0.2,0.0,0.2,0.3,2.7,Mason Jones,3,NaN,NaN,NaN
2,2020-21,24.0,CLE,NBA,SG,28.0,1.0,13.4,1.3,3.6,...,0.5,0.3,0.6,1.3,4.1,Brodric Thomas,3,NaN,NaN,NaN
3,1992-93,24.0,TOT,NBA,PF,75.0,52.0,17.5,3.3,6.3,...,0.3,0.3,1.3,2.5,7.7,Alaa Abdelnaby,3,NaN,NaN,NaN
4,1968-69,22.0,MIL,NBA,C,29.0,NaN,28.9,4.3,12.0,...,NaN,NaN,NaN,3.4,11.0,Zaid Abdul-Aziz,3,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3076,2014-15,25.0,BOS,NBA,C,82.0,59.0,21.1,4.1,7.5,...,0.2,0.6,0.9,2.5,10.2,Tyler Zeller,3,NaN,NaN,NaN
3077,2002-03,25.0,LAC,NBA,C,41.0,1.0,10.0,1.5,4.0,...,0.2,0.2,0.8,1.0,4.4,Wang Zhizhi,3,NaN,NaN,NaN
3078,1996-97,23.0,CHH,NBA,C,36.0,2.0,8.0,0.9,2.4,...,0.1,0.1,0.6,1.2,2.5,George Zidek,3,NaN,NaN,NaN
3079,2019-20,23.0,CLE,NBA,C,22,0,10.0,1.9,3.3,...,0.3,0.2,0.5,1.2,4.4,Ante Zizic,3,NaN,NaN,NaN
3080,2018-19,21.0,TOT,NBA,C,59.0,37.0,17.6,3.6,6.4,...,0.2,0.9,1.2,2.3,8.9,Ivica Zubac,3,NaN,NaN,NaN

In [18]:
values = {"1ST_TEAMNBA": 0, "2nd_TEAMNBA": 0, "3rd_TEAMNBA": 0}
df_final=dfz.fillna(value=values)

In [19]:
df_final

,SEASON,AGE,TEAM,LEAGUE,POS,G,GS,MP,FG,FGA,...,STL,BLK,TOV,PF,PTS,PLAYER,SEASON_COUNT,1ST_TEAMNBA,2nd_TEAMNBA,3rd_TEAMNBA
0,2020-21,19.0,ORL,NBA,SG,26.0,1.0,25.2,4.3,9.7,...,0.6,0.3,1.6,1.5,11.2,R.J. Hampton,3,0.0,0.0,0.0
1,2020-21,22.0,PHI,NBA,SG,6.0,0.0,4.5,0.8,1.5,...,0.2,0.0,0.2,0.3,2.7,Mason Jones,3,0.0,0.0,0.0
2,2020-21,24.0,CLE,NBA,SG,28.0,1.0,13.4,1.3,3.6,...,0.5,0.3,0.6,1.3,4.1,Brodric Thomas,3,0.0,0.0,0.0
3,1992-93,24.0,TOT,NBA,PF,75.0,52.0,17.5,3.3,6.3,...,0.3,0.3,1.3,2.5,7.7,Alaa Abdelnaby,3,0.0,0.0,0.0
4,1968-69,22.0,MIL,NBA,C,29.0,NaN,28.9,4.3,12.0,...,NaN,NaN,NaN,3.4,11.0,Zaid Abdul-Aziz,3,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3076,2014-15,25.0,BOS,NBA,C,82.0,59.0,21.1,4.1,7.5,...,0.2,0.6,0.9,2.5,10.2,Tyler Zeller,3,0.0,0.0,0.0
3077,2002-03,25.0,LAC,NBA,C,41.0,1.0,10.0,1.5,4.0,...,0.2,0.2,0.8,1.0,4.4,Wang Zhizhi,3,0.0,0.0,0.0
3078,1996-97,23.0,CHH,NBA,C,36.0,2.0,8.0,0.9,2.4,...,0.1,0.1,0.6,1.2,2.5,George Zidek,3,0.0,0.0,0.0
3079,2019-20,23.0,CLE,NBA,C,22,0,10.0,1.9,3.3,...,0.3,0.2,0.5,1.2,4.4,Ante Zizic,3,0.0,0.0,0.0
3080,2018-19,21.0,TOT,NBA,C,59.0,37.0,17.6,3.6,6.4,...,0.2,0.9,1.2,2.3,8.9,Ivica Zubac,3,0.0,0.0,0.0

In [20]:
df_final['target'] = (df_final['1ST_TEAMNBA'] + df_final['2nd_TEAMNBA']+df_final['3rd_TEAMNBA']) > 0
df_final

,SEASON,AGE,TEAM,LEAGUE,POS,G,GS,MP,FG,FGA,...,BLK,TOV,PF,PTS,PLAYER,SEASON_COUNT,1ST_TEAMNBA,2nd_TEAMNBA,3rd_TEAMNBA,target
0,2020-21,19.0,ORL,NBA,SG,26.0,1.0,25.2,4.3,9.7,...,0.3,1.6,1.5,11.2,R.J. Hampton,3,0.0,0.0,0.0,False
1,2020-21,22.0,PHI,NBA,SG,6.0,0.0,4.5,0.8,1.5,...,0.0,0.2,0.3,2.7,Mason Jones,3,0.0,0.0,0.0,False
2,2020-21,24.0,CLE,NBA,SG,28.0,1.0,13.4,1.3,3.6,...,0.3,0.6,1.3,4.1,Brodric Thomas,3,0.0,0.0,0.0,False
3,1992-93,24.0,TOT,NBA,PF,75.0,52.0,17.5,3.3,6.3,...,0.3,1.3,2.5,7.7,Alaa Abdelnaby,3,0.0,0.0,0.0,False
4,1968-69,22.0,MIL,NBA,C,29.0,NaN,28.9,4.3,12.0,...,NaN,NaN,3.4,11.0,Zaid Abdul-Aziz,3,0.0,0.0,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3076,2014-15,25.0,BOS,NBA,C,82.0,59.0,21.1,4.1,7.5,...,0.6,0.9,2.5,10.2,Tyler Zeller,3,0.0,0.0,0.0,False
3077,2002-03,25.0,LAC,NBA,C,41.0,1.0,10.0,1.5,4.0,...,0.2,0.8,1.0,4.4,Wang Zhizhi,3,0.0,0.0,0.0,False
3078,1996-97,23.0,CHH,NBA,C,36.0,2.0,8.0,0.9,2.4,...,0.1,0.6,1.2,2.5,George Zidek,3,0.0,0.0,0.0,False
3079,2019-20,23.0,CLE,NBA,C,22,0,10.0,1.9,3.3,...,0.2,0.5,1.2,4.4,Ante Zizic,3,0.0,0.0,0.0,False
3080,2018-19,21.0,TOT,NBA,C,59.0,37.0,17.6,3.6,6.4,...,0.9,1.2,2.3,8.9,Ivica Zubac,3,0.0,0.0,0.0,False

In [21]:
df_final['target'] = df_final['target'].astype(int)
df_final

,SEASON,AGE,TEAM,LEAGUE,POS,G,GS,MP,FG,FGA,...,BLK,TOV,PF,PTS,PLAYER,SEASON_COUNT,1ST_TEAMNBA,2nd_TEAMNBA,3rd_TEAMNBA,target
0,2020-21,19.0,ORL,NBA,SG,26.0,1.0,25.2,4.3,9.7,...,0.3,1.6,1.5,11.2,R.J. Hampton,3,0.0,0.0,0.0,0
1,2020-21,22.0,PHI,NBA,SG,6.0,0.0,4.5,0.8,1.5,...,0.0,0.2,0.3,2.7,Mason Jones,3,0.0,0.0,0.0,0
2,2020-21,24.0,CLE,NBA,SG,28.0,1.0,13.4,1.3,3.6,...,0.3,0.6,1.3,4.1,Brodric Thomas,3,0.0,0.0,0.0,0
3,1992-93,24.0,TOT,NBA,PF,75.0,52.0,17.5,3.3,6.3,...,0.3,1.3,2.5,7.7,Alaa Abdelnaby,3,0.0,0.0,0.0,0
4,1968-69,22.0,MIL,NBA,C,29.0,NaN,28.9,4.3,12.0,...,NaN,NaN,3.4,11.0,Zaid Abdul-Aziz,3,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3076,2014-15,25.0,BOS,NBA,C,82.0,59.0,21.1,4.1,7.5,...,0.6,0.9,2.5,10.2,Tyler Zeller,3,0.0,0.0,0.0,0
3077,2002-03,25.0,LAC,NBA,C,41.0,1.0,10.0,1.5,4.0,...,0.2,0.8,1.0,4.4,Wang Zhizhi,3,0.0,0.0,0.0,0
3078,1996-97,23.0,CHH,NBA,C,36.0,2.0,8.0,0.9,2.4,...,0.1,0.6,1.2,2.5,George Zidek,3,0.0,0.0,0.0,0
3079,2019-20,23.0,CLE,NBA,C,22,0,10.0,1.9,3.3,...,0.2,0.5,1.2,4.4,Ante Zizic,3,0.0,0.0,0.0,0
3080,2018-19,21.0,TOT,NBA,C,59.0,37.0,17.6,3.6,6.4,...,0.9,1.2,2.3,8.9,Ivica Zubac,3,0.0,0.0,0.0,0

In [22]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3081 entries, 0 to 3080
Data columns (total 36 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   SEASON        3081 non-null   object
 1   AGE           3079 non-null   float64
 2   TEAM          3081 non-null   object
 3   LEAGUE        3081 non-null   object
 4   POS           2919 non-null   object
 5   G             3077 non-null   object
 6   GS            2075 non-null   object
 7   MP            2905 non-null   object
 8   FG            3076 non-null   object
 9   FGA           3075 non-null   object
 10  FG%           3061 non-null   object
 11  3P            2315 non-null   object
 12  3PA           2315 non-null   object
 13  3P%           1923 non-null   object
 14  2P            2512 non-null   object
 15  2PA           2512 non-null   object
 16  2P%           2492 non-null   object
 17  eFG%          2499 non-null   object
 18  FT            3076 non-null   object
 19  FTA           3076 non-null   object
 20  FT%           2953 non-null   object
 21  ORB           2490 non-null   object
 22  DRB           2488 non-null   object
 23  TRB           2933 non-null   object
 24  AST           3075 non-null   object
 25  STL           2342 non-null   object
 26  BLK           2346 non-null   object
 27  TOV           2390 non-null   object
 28  PF            3076 non-null   object
 29  PTS           3076 non-null   object
 30  PLAYER        3081 non-null   object
 31  SEASON_COUNT  3081 non-null   int64
 32  1ST_TEAMNBA   3081 non-null   float64
 33  2nd_TEAMNBA   3081 non-null   float64
 34  3rd_TEAMNBA   3081 non-null   float64
 35  target        3081 non-null   int32
dtypes: float64(4), int32(1), int64(1), object(30)
memory usage: 878.6+ KB

In [23]:


df_final.to_pickle('data/for_eda')

In [22]:
df_final=df_final.drop(columns=['1ST_TEAMNBA','2nd_TEAMNBA','3rd_TEAMNBA'])

In [23]:
df_final.columns

Index(['SEASON', 'AGE', 'TEAM', 'LEAGUE', 'POS', 'G', 'GS', 'MP', 'FG', 'FGA',
       'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA',
       'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'PLAYER', 'SEASON_COUNT', 'target'],
      dtype='object')

In [24]:
dfcleaning=df_final.drop('PLAYER',axis=1)
dfcleaning

,SEASON,AGE,TEAM,LEAGUE,POS,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,SEASON_COUNT,target
0,2020-21,19.0,ORL,NBA,SG,26.0,1.0,25.2,4.3,9.7,...,4.2,5.0,2.8,0.6,0.3,1.6,1.5,11.2,3,0
1,2020-21,22.0,PHI,NBA,SG,6.0,0.0,4.5,0.8,1.5,...,0.2,0.7,0.5,0.2,0.0,0.2,0.3,2.7,3,0
2,2020-21,24.0,CLE,NBA,SG,28.0,1.0,13.4,1.3,3.6,...,1.5,1.8,0.9,0.5,0.3,0.6,1.3,4.1,3,0
3,1992-93,24.0,TOT,NBA,PF,75.0,52.0,17.5,3.3,6.3,...,2.8,4.5,0.4,0.3,0.3,1.3,2.5,7.7,3,0
4,1968-69,22.0,MIL,NBA,C,29.0,NaN,28.9,4.3,12.0,...,NaN,13.0,1.1,NaN,NaN,NaN,3.4,11.0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3076,2014-15,25.0,BOS,NBA,C,82.0,59.0,21.1,4.1,7.5,...,3.9,5.7,1.4,0.2,0.6,0.9,2.5,10.2,3,0
3077,2002-03,25.0,LAC,NBA,C,41.0,1.0,10.0,1.5,4.0,...,1.2,1.9,0.2,0.2,0.2,0.8,1.0,4.4,3,0
3078,1996-97,23.0,CHH,NBA,C,36.0,2.0,8.0,0.9,2.4,...,1.1,1.8,0.3,0.1,0.1,0.6,1.2,2.5,3,0
3079,2019-20,23.0,CLE,NBA,C,22,0,10.0,1.9,3.3,...,2.2,3.0,0.3,0.3,0.2,0.5,1.2,4.4,3,0
3080,2018-19,21.0,TOT,NBA,C,59.0,37.0,17.6,3.6,6.4,...,4.2,6.1,1.1,0.2,0.9,1.2,2.3,8.9,3,0

In [25]:
numero=['AGE','G', 'GS', 'MP', 'FG', 'FGA',
       'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA',
       'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS','SEASON_COUNT',
       'target']

In [26]:
from pandas import to_numeric

In [27]:
dfcleaning[numero]=dfcleaning[numero].apply(pd.to_numeric, errors='coerce')

In [28]:
dfcleaning.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3081 entries, 0 to 3080
Data columns (total 32 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   SEASON        3081 non-null   object
 1   AGE           3079 non-null   float64
 2   TEAM          3081 non-null   object
 3   LEAGUE        3081 non-null   object
 4   POS           2919 non-null   object
 5   G             2867 non-null   float64
 6   GS            1865 non-null   float64
 7   MP            2695 non-null   float64
 8   FG            2866 non-null   float64
 9   FGA           2865 non-null   float64
 10  FG%           2851 non-null   float64
 11  3P            2139 non-null   float64
 12  3PA           2139 non-null   float64
 13  3P%           1747 non-null   float64
 14  2P            2336 non-null   float64
 15  2PA           2336 non-null   float64
 16  2P%           2316 non-null   float64
 17  eFG%          2323 non-null   float64
 18  FT            2866 non-null   float64
 19  FTA           2866 non-null   float64
 20  FT%           2743 non-null   float64
 21  ORB           2307 non-null   float64
 22  DRB           2305 non-null   float64
 23  TRB           2723 non-null   float64
 24  AST           2865 non-null   float64
 25  STL           2174 non-null   float64
 26  BLK           2175 non-null   float64
 27  TOV           2212 non-null   float64
 28  PF            2866 non-null   float64
 29  PTS           2866 non-null   float64
 30  SEASON_COUNT  3081 non-null   int64
 31  target        3081 non-null   int32
dtypes: float64(26), int32(1), int64(1), object(4)
memory usage: 782.3+ KB

In [29]:
dfcleaning.isna().sum()

SEASON             0
AGE                2
TEAM               0
LEAGUE             0
POS              162
G                214
GS              1216
MP               386
FG               215
FGA              216
FG%              230
3P               942
3PA              942
3P%             1334
2P               745
2PA              745
2P%              765
eFG%             758
FT               215
FTA              215
FT%              338
ORB              774
DRB              776
TRB              358
AST              216
STL              907
BLK              906
TOV              869
PF               215
PTS              215
SEASON_COUNT       0
target             0
dtype: int64

In [30]:
low_null= ['G', 'MP', 'FG', 'FGA',
       'FG%', '3P', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA',
       'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',]

In [31]:
dfcleaning.columns

Index(['SEASON', 'AGE', 'TEAM', 'LEAGUE', 'POS', 'G', 'GS', 'MP', 'FG', 'FGA',
       'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA',
       'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'SEASON_COUNT', 'target'],
      dtype='object')

In [32]:
dfcleaning.target.value_counts(normalize = True)

0    0.925349
1    0.074651
Name: target, dtype: float64

In [33]:
dfcleaning['3P%']=dfcleaning['3P%'].fillna(0)

In [34]:
dfcleaning.drop('GS',axis=1)

,SEASON,AGE,TEAM,LEAGUE,POS,G,MP,FG,FGA,FG%,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,SEASON_COUNT,target
0,2020-21,19.0,ORL,NBA,SG,26.0,25.2,4.3,9.7,0.439,...,4.2,5.0,2.8,0.6,0.3,1.6,1.5,11.2,3,0
1,2020-21,22.0,PHI,NBA,SG,6.0,4.5,0.8,1.5,0.556,...,0.2,0.7,0.5,0.2,0.0,0.2,0.3,2.7,3,0
2,2020-21,24.0,CLE,NBA,SG,28.0,13.4,1.3,3.6,0.366,...,1.5,1.8,0.9,0.5,0.3,0.6,1.3,4.1,3,0
3,1992-93,24.0,TOT,NBA,PF,75.0,17.5,3.3,6.3,0.518,...,2.8,4.5,0.4,0.3,0.3,1.3,2.5,7.7,3,0
4,1968-69,22.0,MIL,NBA,C,29.0,28.9,4.3,12.0,0.363,...,NaN,13.0,1.1,NaN,NaN,NaN,3.4,11.0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3076,2014-15,25.0,BOS,NBA,C,82.0,21.1,4.1,7.5,0.549,...,3.9,5.7,1.4,0.2,0.6,0.9,2.5,10.2,3,0
3077,2002-03,25.0,LAC,NBA,C,41.0,10.0,1.5,4.0,0.383,...,1.2,1.9,0.2,0.2,0.2,0.8,1.0,4.4,3,0
3078,1996-97,23.0,CHH,NBA,C,36.0,8.0,0.9,2.4,0.388,...,1.1,1.8,0.3,0.1,0.1,0.6,1.2,2.5,3,0
3079,2019-20,23.0,CLE,NBA,C,22.0,10.0,1.9,3.3,0.569,...,2.2,3.0,0.3,0.3,0.2,0.5,1.2,4.4,3,0
3080,2018-19,21.0,TOT,NBA,C,59.0,17.6,3.6,6.4,0.559,...,4.2,6.1,1.1,0.2,0.9,1.2,2.3,8.9,3,0

In [35]:
import pickle

dfcleaning.to_pickle('data/cleaned_data')